services:
  mongodb:             
    image: mongo
    ports:
      - 27017:27017    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=example 
    volumes:
      - mongodb_data:/data/db   
      - ./import-database:/docker-entrypoint-initdb.d 
    #command: ["--bind_ip_all"] #expose to all netwokrs
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb


  spring-app:
    image: edgaras87/car-trader-backend
    #container_name: my-spring-app-container    
    ports:
      - "5000:5000"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

    depends_on:
      - mongodb
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/car-trader
#      SPRING_DATA_MONGODB_DATABASE: car-trader



  angular-app:
    image: edgaras87/car-trader-frontend
    ports:
      - "80:80"
    depends_on:
      - spring-app
#        condition: service_healthy






#  import-data:
#    build:
#      context: ./import-data
#      dockerfile: Dockerfile
#    depends_on:
#      - mongodb
#    #volumes:
#    #  - ./:/docker-entrypoint-initdb.d
volumes:
  mongodb_data: {}
#      driver: local 



