export enum Checkbox {

  //*equipmentInfo
  // chassis
  paddleshifter ='Paddle shifters',
  // condition
  nonSmoking = 'Non-smoking vechicle',
  serviceHistory = 'Full Service History',
  warranty ='Warranty/Factory Warranty',

  //*equipmentInfo

  //interiorExterior
  metalic = 'Metalic',

  //safety
  abs = 'Antilocking system (ABS)',
  esp = 'Electronic stability program (ESP)',
  asr = 'Traction control (ASR)',
  hillStart = 'Hill-start assist',
  fatigueWarning = 'Fatigue warning system',
  laneChange = 'Lane change assist',
  blindSpot = 'Blind spot assist',
  dimmingMirror = 'Auto-dimming interior mirror',
  nightVision = 'Night vision assist',
  emergencyBrake = 'Emergency brake assist',
  emergencyCall = 'Emergency call system',
  trafficSignRecog = 'Traffic sign recognition',
  //cruise = '',
  speedLimit = 'Speed limit control system',
  distanceWarning = 'Distance warning system',
  //airbags = '',
  isofixChild = 'Isofix (child seat anchor points)',
  isofixPassenger = 'Passenger seat Isofix point',
  //headlights = '',
  headlightsWasher = 'Headlight washer system',
  alarm = 'Alarm system',
  immobilizer = 'Engine immobilizer',

  //comfort =
  //climatisation = '',
  auxiliaryHeating = 'Auxiliary heating',
  heatedWindshield = 'Heated windshield',
  heatedSteeringWheel = 'Heated steering wheel',
  selfSteering = 'Self-steering systems',
  //parkingAssist = '',
  //camera = '',
  //seatsHeated = '',
  //seatsElectricAdjustable = '',
  seatsSport = 'Sport seats',
  armRest = 'Arm rest',
  seatsMassage = 'Massage seats',
  seatsMemory = 'Seat memory',
  seatsVentilation = 'Seat ventilation',
  seatsFoldflat = 'Fold flat passenger seat',
  electricWindow = 'Electric windows',
  electricMirror = 'Electric side mirror',
  electricTailgate = 'Electric tailgate',
  centralLocking = 'Central locking',
  keyless = 'Keyless system',
  lightSensor = 'Light sensor',
  rainSensor = 'Rain sensor',
  powerAssistSteering = 'Power Assisted Steering',
  leatherSteeringWheel = 'Leather steering wheel',

  //infotainment
  radio = 'Tuner/radio',
  dabRadio = 'DAB radio',
  cdPlayer = 'CD player',
  tv = 'TV',
  navigationSystem = 'Navigation system',
  soundSystem = 'Sound system',
  touchScreen = 'Touchscreen',
  voiceControl = 'Voice control',
  multifunctionSteeringWheel = 'Multifunction steering wheel',
  handsFreeKit = 'Hands-free kit',
  usbPort = 'USB port',
  bluetooth = 'Bluetooth',
  appleCarPlay = 'Apple CarPlay',
  androidAuto = 'Android Auto',
  wlanWifiHotspot = 'WLAN / WiFi hotspot',
  integratedMusicStreaming = 'Integrated music streaming',
  inductionChargingForSmartphones = 'Induction charging for smartphones',
  onboardComputer = 'On-board computer',
  headupDisplay = 'Head-up display',
  digitalCockpit = 'Digital cockpit',

  //extra
  alloyWheels = 'Alloy wheels',
  summerTyres = 'Summer tyres',
  winterTyres = 'Winter tyres',
  allSeasonTyres = 'All season tyres',
  //breakdownKit ='',
  tyrePressureMonitoring = 'Tyre pressure monitoring',
  winterPackage = 'Winter package',
  smokerPackage = "Smoker's package",
  sportsPackage = 'Sports package',
  sportsSuspension = 'Sports suspension',
  airSuspension = 'Air suspension',
  //trailerCoupling ='',
  cargoBarrier = 'Cargo barrier',
  skiBag = 'Ski bag',
  sunroof = 'Sunroof',
  panoramicRoof = 'Panoramic roof',
  roofRack = 'Roof rack',
  disabledAccessible = 'Disabled accessible',
  taxi = 'Taxi',

}
