

server:
  port: 5000
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-exception: true


spring:
  config:
    import: env.yml
  data:
    mongodb:

      #uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@portfolio.g8ztuqs.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
      #auto-index-creation: true

      #authentication-database: admin
      #username: rootuser
      #password: rootpass


      # ==== mongodb atlas =====
      #uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@portfolio.g8ztuqs.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
      #uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@portfolio.g8ztuqs.mongodb.net/${DB_NAME}?retryWrites=true&w=majority
      #uri: mongodb+srv://edge:yLZ9Yhjit5H7jbOL@portfolio.g8ztuqs.mongodb.net/car-trader?retryWrites=true&w=majority
      #auto-index-creation: true

      # ==== mongodb localhost =====
      #authentication-database: admin
      #username: root
      #password: example

      #database: car-trader
      #port: 27017
      #host: localhost
      # for unique emails
      # for indexing location to calc distance
      #auto-index-creation: true

      # ==== mongodb docker-compose
      #uri: mongodb://mongodb/car-trader?auto-index-creation=true
      uri: mongodb://root:example@mongodb/car-trader?authSource=admin&auto-index-creation=true


  #mvc:
  #  pathmatch:
  #    matching-strategy: ANT_PATH_MATCHER # http://localhost:8080/swagger-ui/

# App properties
cartrader:
  app:
    jwtSecret: cartraderSecretKeylooooooooooooooooooooooooooooooooooooooooooooooong
    jwtExpirationMs: 864000000
    #jwtExpirationMs: 10000




